// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// GoTestContext is an autogenerated mock type for the GoTestContext type
type GoTestContext struct {
	mock.Mock
}

// Fail provides a mock function with given fields:
func (_m *GoTestContext) Fail() {
	_m.Called()
}

// FailNow provides a mock function with given fields:
func (_m *GoTestContext) FailNow() {
	_m.Called()
}

// Log provides a mock function with given fields: args
func (_m *GoTestContext) Log(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Run provides a mock function with given fields: _a0, _a1
func (_m *GoTestContext) Run(_a0 string, _a1 func(*testing.T)) bool {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, func(*testing.T)) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
